name: mystartup-snap # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Autostarts flasktemp when the device is started.
description: |
  This is a snap that acts as a script in order 
  to autostart any snap that is already 
  registered in the device
grade: devel
confinement: devmode  # use 'strict' once you have the right plugs and slots

parts:
  startup:
    # See 'snapcraft plugins'
    plugin: dump
    source: src/

apps:
  mystartup:
    command: startup
    daemon: simple
    restart-condition: never
